kind: pipeline
type: docker
name: default

steps:
- name: build
  image: archlinux:latest
  commands:
  - pacman -Syu --noconfirm --needed base-devel libvncserver libxkbcommon libdrm libva git cmake clang
  - export CFLAGS="-pipe -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security"
  - CC=gcc cmake -B gcc-out
  - cmake --build gcc-out
  - CC=clang cmake -B clang-out
  - cmake --build clang-out

trigger:
  branch:
  - dev
  event:
    exclude:
    - pull_request
